# Generated by Django 5.2.3 on 2025-06-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_products_options_alter_products_createduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantcombination',
            name='combination',
            field=models.CharField(max_length=255),
        ),
    ]
