# Generated by Django 5.2.3 on 2025-06-26 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_productvariantcombination_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.products'),
            preserve_default=False,
        ),
    ]
