# Generated by Django 5.2.3 on 2025-06-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stocktransaction_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
